"""Terraform HCL export engine.

Pure functions: config-export objects in, HCL text out. No DB access, no
storage access, no licensing here (routes enforce the gate). Deliberately
self-contained so the engine can be lifted into a standalone product later.

The schemas in app/core/tfschemas/*.json are the OFFICIAL provider schemas,
generated by tools/gen_tf_schemas.py from `terraform providers schema -json`
for goauthentik/authentik, okta/okta and auth0/auth0. Every emitted attribute
is validated against them. Anything the official provider cannot represent is
dropped AND reported - never silently.

Secrets are NEVER emitted, even when the snapshot holds them: any sensitive
attribute becomes a `var.` reference declared in variables.tf (sensitive =
true). Cross-object references (an application's provider, a binding's
target) are rewritten to Terraform references when the referenced object is
part of the same export, so a bundle applied to a fresh tenant wires itself
together instead of carrying meaningless source-instance ids (provider pks
are per-instance - the clone lesson, applied to HCL).
"""
import json
import os
import re
from functools import lru_cache

_SCHEMA_DIR = os.path.join(os.path.dirname(__file__), "tfschemas")

# Source fields that are export metadata, never Terraform arguments.
_META_FIELDS = {"component", "meta_model_name", "verbose_name",
                "verbose_name_plural", "managed", "created", "last_updated",
                "object_uid", "_links", "_embedded"}

# Attribute names that look secret even when the schema does not flag them.
_SECRET_RE = re.compile(
    r"(secret|password|private_key|credentials|api_key|shared_key|"
    r"bind_password|sym_key|client_keys)", re.I)

# Authentik attrs that reference other objects by pk/uuid (mirror of the
# adapter's ref knowledge, duplicated here to keep the engine standalone).
_AK_REF_ATTRS = {
    "provider", "providers", "backchannel_providers", "protocol_provider",
    "target", "policy", "group", "user", "stage", "flow", "source",
    "authorization_flow", "authentication_flow", "invalidation_flow",
    "enrollment_flow", "recovery_flow", "unenrollment_flow",
    "user_settings_flow", "device_code_flow", "configure_flow",
    "certificate", "signing_kp", "verification_kp", "encryption_kp",
    "property_mappings", "property_mappings_group", "jwks_sources",
    "configuration_stages", "protocol_providers",
}

# Okta built-in/system apps: Terraform cannot create or manage these.
_OKTA_SYSTEM_APPS = {"saasure", "okta_enduser", "okta_browser_plugin",
                     "okta_account_settings", "okta_iga_reviewer",
                     "okta_flow_sso", "flow", "okta_admin_console"}

# Okta `name` values that mean CUSTOM app (anything else is an OIN catalog
# name and becomes preconfigured_app).
_OKTA_CUSTOM_APP_NAMES = {"oidc_client", "template_saml_2_0",
                          "template_saml_1_1", "bookmark", "template_swa",
                          "template_swa3links", "template_sps",
                          "template_basic_auth", "template_wsfed"}

# Terraform meta-blocks that must never be emitted from data.
_SKIP_BLOCKS = {"timeouts"}

# Attribute emission order: identity first, then description and core
# type/status fields - the convention every provider's example templates
# share - then the rest in stable (alphabetical) order.
_ATTR_PRIORITY = ["label", "name", "slug", "description", "type", "status",
                  "priority"]


def _attr_order(attrs) -> list:
    pri = [a for a in _ATTR_PRIORITY if a in attrs]
    return pri + sorted(a for a in attrs if a not in _ATTR_PRIORITY)

# Okta application signOnMode -> Terraform resource.
_OKTA_APP_BY_MODE = {
    "OPENID_CONNECT": "okta_app_oauth",
    "SAML_2_0": "okta_app_saml",
    "SAML_1_1": "okta_app_saml",
    "AUTO_LOGIN": "okta_app_auto_login",
    "BROWSER_PLUGIN": "okta_app_swa",
    "SECURE_PASSWORD_STORE": "okta_app_secure_password_store",
    "BOOKMARK": "okta_app_bookmark",
    "BASIC_AUTH": "okta_app_basic_auth",
}

# Okta policy rtypes (ours) -> Terraform resource.
_OKTA_POLICY_BY_RTYPE = {
    "policies_signon": "okta_policy_signon",
    "policies_password": "okta_policy_password",
    "policies_mfa": "okta_policy_mfa",
    "policies_access": "okta_app_signon_policy",
}

# Okta IdP type -> Terraform resource (anything else is a social provider).
_OKTA_IDP_BY_TYPE = {"OIDC": "okta_idp_oidc", "SAML2": "okta_idp_saml"}

# Auth0 rtypes (ours) -> Terraform resource, all 1:1.
_AUTH0_BY_RTYPE = {
    "clients": "auth0_client",
    "client_grants": "auth0_client_grant",
    "connections": "auth0_connection",
    "resource_servers": "auth0_resource_server",
    "roles": "auth0_role",
    "rules": "auth0_rule",
    "actions": "auth0_action",
    "tenant_settings": "auth0_tenant",
    "branding": "auth0_branding",
    "custom_domains": "auth0_custom_domain",
}

# Authentik flat rtypes (ours) -> Terraform resource (polymorphic rtypes -
# providers, stages, policies, property_mappings, sources - derive from the
# object's `component`, e.g. ak-provider-oauth2-form -> provider_oauth2).
_AK_BY_RTYPE = {
    "applications": "authentik_application",
    "flows": "authentik_flow",
    "groups": "authentik_group",
    "brands": "authentik_brand",
    "outposts": "authentik_outpost",
    "certificates": "authentik_certificate_key_pair",
    "policy_bindings": "authentik_policy_binding",
    "flow_stage_bindings": "authentik_flow_stage_binding",
}


@lru_cache(maxsize=None)
def load_schema(provider: str) -> dict:
    """Load the trimmed official provider schema (authentik|okta|auth0)."""
    with open(os.path.join(_SCHEMA_DIR, f"{provider}.json")) as f:
        return json.load(f)


def _camel_to_snake(name: str) -> str:
    return re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name).lower()


def sanitize_label(name: str) -> str:
    """Turn an object name/slug into a valid HCL resource label."""
    label = re.sub(r"[^a-z0-9_]", "_", str(name or "unnamed").lower())
    label = re.sub(r"_+", "_", label).strip("_") or "unnamed"
    if not label[0].isalpha():
        label = "r_" + label
    return label


def _escape(s: str) -> str:
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    s = s.replace("${", "$${").replace("%{", "%%{")
    return s.replace("\r", "\\r").replace("\n", "\\n").replace("\t", "\\t")


def _render(value, indent: int = 1) -> str:
    """Render a python value as an HCL expression."""
    pad = "  " * indent
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        if "\n" in value:
            eot = "EOT"
            while eot in value:
                eot += "_"
            body = value.rstrip("\n").replace("${", "$${").replace("%{", "%%{")
            return f"<<-{eot}\n{body}\n{pad}{eot}"
        return f'"{_escape(value)}"'
    if isinstance(value, list):
        if not value:
            return "[]"
        items = [f"{pad}  {_render(v, indent + 1)}" for v in value]
        return "[\n" + ",\n".join(items) + f"\n{pad}]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = []
        for k, v in value.items():
            key = k if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", k) else f'"{_escape(k)}"'
            lines.append(f"{pad}  {key} = {_render(v, indent + 1)}")
        return "{\n" + "\n".join(lines) + f"\n{pad}}}"
    return "null"


def _schema_type_is_string(t) -> bool:
    return t == "string"


def _tf_var_type(t) -> str:
    """Terraform variable type expression for a schema attribute type."""
    if isinstance(t, str):
        return t if t in ("string", "number", "bool") else "any"
    if (isinstance(t, list) and len(t) == 2 and t[0] in ("list", "set", "map")
            and isinstance(t[1], str) and t[1] in ("string", "number", "bool")):
        return f"{t[0]}({t[1]})"
    return "any"


def tf_resource_for(provider: str, rtype: str, obj: dict):
    """Map one of our export objects to its Terraform resource type.

    Returns (tf_type, None) on success or (None, reason) when the official
    provider cannot represent the object.
    """
    resources = load_schema(provider)["resources"]

    def _check(name, why_missing=None):
        if name in resources:
            return name, None
        return None, (why_missing or
                      f"the official provider has no {name} resource")

    if provider == "authentik":
        if rtype == "blueprints":
            return None, "blueprints are instance-managed, not exported"
        if rtype in _AK_BY_RTYPE:
            return _check(_AK_BY_RTYPE[rtype])
        component = obj.get("component") or ""
        if not component:
            return None, "built-in object (no component), not manageable"
        name = "authentik_" + component.removeprefix("ak-") \
            .removesuffix("-form").replace("-", "_")
        return _check(name)

    if provider == "okta":
        if rtype == "apps":
            if (obj.get("name") or "") in _OKTA_SYSTEM_APPS:
                return None, "Okta system app - not manageable via Terraform"
            mode = obj.get("signOnMode") or obj.get("sign_on_mode") or ""
            if mode in _OKTA_APP_BY_MODE:
                return _check(_OKTA_APP_BY_MODE[mode])
            return None, f"unsupported app sign-on mode {mode or '(none)'}"
        if rtype == "groups":
            if (obj.get("type") or "").upper() == "BUILT_IN":
                return None, "built-in Okta group, not manageable"
            return _check("okta_group")
        if rtype in _OKTA_POLICY_BY_RTYPE:
            return _check(_OKTA_POLICY_BY_RTYPE[rtype])
        if rtype == "authorization_servers":
            return _check("okta_auth_server")
        if rtype == "idps":
            t = (obj.get("type") or "").upper()
            return _check(_OKTA_IDP_BY_TYPE.get(t, "okta_idp_social"))
        if rtype == "network_zones":
            return _check("okta_network_zone")
        if rtype == "event_hooks":
            return _check("okta_event_hook")
        if rtype == "inline_hooks":
            return _check("okta_inline_hook")
        if rtype == "user_types":
            return _check("okta_user_type")
        if rtype == "profile_mappings":
            return _check("okta_profile_mapping")
        if rtype == "user_schemas":
            return None, ("user schemas map to per-property Terraform "
                          "resources; not exported in this version")
        return None, f"no Terraform mapping for {rtype}"

    if provider == "auth0":
        if rtype in _AUTH0_BY_RTYPE:
            return _check(_AUTH0_BY_RTYPE[rtype])
        return None, f"no Terraform mapping for {rtype}"

    return None, f"unknown provider {provider}"


def _flatten(provider: str, rtype: str, obj: dict, attrs=None) -> dict:
    """Normalize a source object to a flat snake_case dict of candidate args.
    `attrs` (the target resource's schema attribute names) enables mappings
    that need to know what the provider accepts (e.g. app_settings_json)."""
    if provider == "okta":
        flat = {}
        for k, v in obj.items():
            if k in ("settings", "credentials", "_links", "_embedded"):
                continue
            flat[_camel_to_snake(k)] = v
        settings = obj.get("settings") or {}
        # oauthClient keys are already snake_case (OAuth spec names); the
        # other settings groups are camelCase - normalize everything.
        for group in ("oauthClient", "app", "signOn", "notifications"):
            for k, v in (settings.get(group) or {}).items():
                flat.setdefault(_camel_to_snake(k), v)
        creds = obj.get("credentials") or {}
        client_id = (creds.get("oauthClient") or {}).get("client_id")
        if client_id:
            flat.setdefault("client_id", client_id)
        if rtype == "profile_mappings":
            src, tgt = obj.get("source") or {}, obj.get("target") or {}
            if isinstance(src, dict) and src.get("id"):
                flat.pop("source", None)
                flat["source_id"] = src["id"]
            if isinstance(tgt, dict) and tgt.get("id"):
                flat.pop("target", None)
                flat["target_id"] = tgt["id"]
            props = obj.get("properties")
            if isinstance(props, dict):
                flat.pop("properties", None)
                flat.setdefault("mappings", [
                    {"id": k, "expression": (v or {}).get("expression"),
                     "pushStatus": (v or {}).get("pushStatus")}
                    for k, v in props.items()])
        if rtype.startswith("policies_"):
            # The people/groups condition maps to groups_included on the
            # policy resources; the rest of `conditions` stays reported.
            inc = ((((obj.get("conditions") or {}).get("people") or {})
                    .get("groups")) or {}).get("include")
            if inc:
                flat.setdefault("groups_included", inc)
        if rtype == "apps":
            flat.setdefault("label", obj.get("label") or obj.get("name"))
            # OIN catalog name -> preconfigured_app; custom-app template
            # names carry no information.
            nm = flat.pop("name", None)
            if nm and nm not in _OKTA_CUSTOM_APP_NAMES:
                flat.setdefault("preconfigured_app", nm)
            # visibility / accessibility structures -> their flat arguments.
            vis = obj.get("visibility") or {}
            flat.pop("visibility", None)
            hide = vis.get("hide") or {}
            if hide.get("web") is not None:
                flat.setdefault("hide_web", hide["web"])
            if hide.get("iOS") is not None:
                flat.setdefault("hide_ios", hide["iOS"])
            if vis.get("autoSubmitToolbar") is not None:
                flat.setdefault("auto_submit_toolbar", vis["autoSubmitToolbar"])
            if vis.get("appLinks"):
                flat.setdefault("app_links_json", vis["appLinks"])
            acc = obj.get("accessibility") or {}
            flat.pop("accessibility", None)
            if acc.get("selfService") is not None:
                flat.setdefault("accessibility_self_service", acc["selfService"])
            if acc.get("errorRedirectUrl"):
                flat.setdefault("accessibility_error_redirect_url",
                                acc["errorRedirectUrl"])
            if acc.get("loginRedirectUrl"):
                flat.setdefault("accessibility_login_redirect_url",
                                acc["loginRedirectUrl"])
            # API names that differ from the provider's argument names.
            if flat.get("application_type") and "type" not in flat:
                flat["type"] = flat.pop("application_type")
            if flat.get("sso_acs_url") and "sso_url" not in flat:
                flat["sso_url"] = flat.pop("sso_acs_url")
            unt = creds.get("userNameTemplate") or {}
            if unt.get("template"):
                flat.setdefault("user_name_template", unt["template"])
            if unt.get("type"):
                flat.setdefault("user_name_template_type", unt["type"])
            if unt.get("pushStatus"):
                flat.setdefault("user_name_template_push_status",
                                unt["pushStatus"])
            # OIN per-app settings with no native argument go to
            # app_settings_json - the provider's own mechanism for them.
            if attrs and "app_settings_json" in attrs:
                leftovers = {k: v for k, v in (settings.get("app") or {}).items()
                             if _camel_to_snake(k) not in attrs
                             and v is not None}
                if leftovers:
                    flat.setdefault("app_settings_json", leftovers)
                    for k in leftovers:   # captured - don't report as dropped
                        flat.pop(_camel_to_snake(k), None)
        # Non-app types (groups, user types...) keep their name/description
        # inside `profile`; anything else in the profile is a custom attribute
        # (okta_group exposes those as jsonencoded custom_profile_attributes).
        prof = obj.get("profile")
        if rtype != "apps" and isinstance(prof, dict):
            flat.pop("profile", None)
            custom = {}
            for k, v in prof.items():
                sk = _camel_to_snake(k)
                if sk in ("name", "description"):
                    flat.setdefault(sk, v)
                else:
                    custom[k] = v
            if custom:
                flat.setdefault("custom_profile_attributes", custom)
        if rtype == "network_zones":
            def _s(x):   # {country, region} dicts -> provider strings
                if isinstance(x, dict):
                    return x.get("region") or x.get("country") or str(x)
                return x
            # Enhanced dynamic zones return {include, exclude} dicts where the
            # provider wants flat sets. Unmappable leftovers keep a distinct
            # key so they land in the dropped-fields report, never silently.
            for src, inc, exc in (("asns", "asns", "asns_exclude"),
                                  ("locations", "dynamic_locations",
                                   "dynamic_locations_exclude"),
                                  ("ip_service_categories",
                                   "ip_service_categories_include",
                                   "ip_service_categories_exclude")):
                v = flat.get(src)
                if isinstance(v, dict):
                    flat.pop(src)
                    if v.get("include"):
                        flat[inc] = [_s(x) for x in v["include"]]
                    if v.get("exclude"):
                        flat[exc] = [_s(x) for x in v["exclude"]]
            # Plain dynamic zones carry a flat locations list.
            if isinstance(flat.get("locations"), list):
                flat["dynamic_locations"] = [_s(x) for x in flat.pop("locations")]
        return flat
    # authentik and auth0 payloads are already snake_case.
    flat = dict(obj)
    if provider == "authentik":
        if rtype == "applications" and flat.get("provider") is not None:
            # API field `provider` = the TF argument `protocol_provider`.
            flat.setdefault("protocol_provider", flat.pop("provider"))
        if rtype == "providers" and isinstance(flat.get("redirect_uris"), list):
            # API redirect_uris = TF allowed_redirect_uris (same shape:
            # list of {matching_mode, url} maps).
            flat.setdefault("allowed_redirect_uris", flat.pop("redirect_uris"))
        if rtype == "outposts" and flat.get("providers") is not None:
            # API field `providers` = the TF argument `protocol_providers`.
            flat.setdefault("protocol_providers", flat.pop("providers"))
    if provider == "auth0" and rtype == "clients" \
            and "cross_origin_authentication" in flat:
        flat.setdefault("cross_origin_auth",
                        flat.pop("cross_origin_authentication"))
    return flat


def _uses_slug_id(tf_type: str) -> bool:
    """Authentik resources whose Terraform id is the SLUG (the provider does
    SetId(res.Slug): applications, flows, sources - verified in provider
    source). Imports use the slug; references to them must use .uuid."""
    return (tf_type in ("authentik_application", "authentik_flow")
            or tf_type.startswith("authentik_source_"))


def import_id(provider: str, rtype: str, tf_type: str, obj: dict):
    """The id a `terraform import` of this resource expects."""
    if provider == "authentik" and _uses_slug_id(tf_type):
        return obj.get("slug")
    return object_id(provider, rtype, obj)


def object_id(provider: str, rtype: str, obj: dict):
    """The pk/id other objects use to REFERENCE this one (ref index key)."""
    if provider == "authentik":
        return (obj.get("pk") or obj.get("pbm_uuid") or obj.get("uuid")
                or obj.get("brand_uuid"))
    if provider == "okta":
        return obj.get("id")
    if provider == "auth0":
        if rtype == "clients":
            return obj.get("client_id")
        if rtype in ("tenant_settings", "branding"):
            return None  # singletons; nothing meaningful to import by id
        return obj.get("id")
    return None


def display_name(provider: str, rtype: str, obj: dict) -> str:
    # Auth0 client grants have no name of their own - show the wiring.
    # (client_id would win the fallback chain below and read as noise.)
    if provider == "auth0" and rtype == "client_grants":
        return f"{obj.get('client_id', '?')} to {obj.get('audience', '?')}"
    # label BEFORE name: for Okta apps `name` is the catalog id
    # (duoadminpanel); `label` is the human name (Duo Admin Panel).
    prof = obj.get("profile")
    prof_name = prof.get("name") if isinstance(prof, dict) else None
    return str(obj.get("label") or obj.get("name") or prof_name
               or obj.get("slug") or obj.get("domain") or obj.get("client_id")
               or obj.get("id") or obj.get("pk") or "unnamed")


class _Labels:
    """Dedupe HCL labels within one export."""

    def __init__(self):
        self._used = set()

    def take(self, base: str) -> str:
        label, n = base, 2
        while label in self._used:
            label, n = f"{base}_{n}", n + 1
        self._used.add(label)
        return label


def _ref_expr(value, ref_index: dict, provider: str, attr: str):
    """Rewrite a cross-object id to a Terraform reference when the target is
    part of this export. Strings must match exactly; ints only for attrs the
    provider is known to use as references (guards against order/priority
    style numerics colliding with a pk)."""
    if not ref_index:
        return None

    def _expr(t, label):
        # Slug-id resources: their .id is the slug; peers reference the uuid.
        return f"{t}.{label}.{'uuid' if _uses_slug_id(t) else 'id'}"

    if isinstance(value, str) and value in ref_index:
        return _expr(*ref_index[value])
    if isinstance(value, int) and (provider != "authentik"
                                   or attr in _AK_REF_ATTRS):
        hit = ref_index.get(str(value))
        if hit:
            return _expr(*hit)
    return None


def _emit_attr_value(value, meta, ref_index, provider, attr, indent=1):
    ref = _ref_expr(value, ref_index, provider, attr)
    if ref:
        return ref
    if isinstance(value, list):
        refs = [_ref_expr(v, ref_index, provider, attr) for v in value]
        if any(refs):
            items = [r or _render(v, indent + 1)
                     for r, v in zip(refs, value)]
            pad = "  " * indent
            return "[\n" + ",\n".join(f"{pad}  {i}" for i in items) + f"\n{pad}]"
    if _schema_type_is_string(meta.get("type")) and isinstance(value, (dict, list)):
        return f"jsonencode({_render(value, indent)})"
    return _render(value, indent)


def _emit_blocks(schema, flat, consumed, ref_index, provider):
    """Emit nested blocks (attribute_statements, groups_claim, auth0 client
    blocks...) validated against the schema's block specs. Source values are
    dicts or lists of dicts under the block's (snake_case) name."""
    out = []
    for bname in sorted(schema.get("blocks", {})):
        if bname in _SKIP_BLOCKS:
            continue
        consumed.add(bname)
        val = flat.get(bname)
        if not val:
            continue
        spec = schema["blocks"][bname]
        battrs = (spec.get("schema") or {}).get("attrs") or {}
        entries = val if isinstance(val, list) else [val]
        for e in entries:
            if not isinstance(e, dict):
                continue
            es = {_camel_to_snake(k): v for k, v in e.items()}
            body = []
            for an in _attr_order(battrs):
                m = battrs[an]
                # Unlike resource-level id (Terraform meta), a block-level id
                # can be a REQUIRED argument (okta_profile_mapping mappings).
                if (an == "id" and not m["req"]) or not (m["req"] or m["opt"]):
                    continue
                v = es.get(an)
                if v is None or v == "" or v == []:
                    continue
                body.append(f"    {an} = "
                            f"{_emit_attr_value(v, m, ref_index, provider, an, 2)}")
            if body:
                out.append(f"  {bname} {{\n" + "\n".join(body) + "\n  }")
    return out


def emit_resource(provider: str, tf_type: str, obj: dict, rtype: str,
                  label: str, ref_index=None):
    """Emit one resource block.

    Returns (hcl, dropped_fields, variables) where variables is a list of
    (var_name, description) for secrets/required-but-absent values.
    """
    schema = load_schema(provider)["resources"][tf_type]
    attrs = schema["attrs"]
    flat = _flatten(provider, rtype, obj, attrs)
    ref_index = ref_index or {}
    lines = [f'resource "{tf_type}" "{label}" {{']
    variables, consumed = [], set()

    for name in _attr_order(attrs):
        meta = attrs[name]
        settable = meta["req"] or meta["opt"]
        if name == "id" or not settable:
            continue
        value = flat.get(name)
        consumed.add(name)
        secret = meta.get("sensitive") or _SECRET_RE.search(name)
        if secret and (value not in (None, "") or meta["req"]):
            var = f"{label}_{name}"
            variables.append((var, f"{tf_type}.{label} {name}",
                              _tf_var_type(meta.get("type"))))
            lines.append(f"  {name} = var.{var}")
            continue
        if value is None or value == "":
            if meta["req"]:
                var = f"{label}_{name}"
                variables.append((var, f"{tf_type}.{label} {name} (required, "
                                       "not present in the export)",
                                  _tf_var_type(meta.get("type"))))
                lines.append(f"  {name} = var.{var}")
            elif name in flat or name == "description":
                # The source object HAS this field, just blank - keep it
                # visible as a commented line (inert to Terraform) instead of
                # silently omitting it. `description` always shows when the
                # schema supports it, even if the API omitted the key: it is
                # the one field humans always look for.
                # No space after # - deleting the single # character leaves
                # the line perfectly indented and ready to use.
                t = meta.get("type")
                if _schema_type_is_string(t):
                    lines.append(f'  #{name} = ""')
                elif isinstance(t, list) and t and t[0] in ("list", "set"):
                    lines.append(f"  #{name} = []")
                elif isinstance(t, list) and t and t[0] == "map":
                    lines.append(f"  #{name} = {{}}")
            continue
        lines.append(f"  {name} = "
                     f"{_emit_attr_value(value, meta, ref_index, provider, name)}")

    lines.extend(_emit_blocks(schema, flat, consumed, ref_index, provider))
    lines.append("}")

    dropped = sorted(k for k, v in flat.items()
                     if k not in consumed and k not in _META_FIELDS
                     and not k.endswith("_obj") and v not in (None, "", [], {})
                     and k not in ("pk", "id"))
    return "\n".join(lines), dropped, variables


def emit_import(tf_type: str, label: str, import_id) -> str:
    return (f"import {{\n  to = {tf_type}.{label}\n"
            f'  id = "{import_id}"\n}}')


_PROVIDER_STUBS = {
    "authentik": (
        'provider "authentik" {\n  url   = var.authentik_url\n'
        '  token = var.authentik_token\n}\n',
        [("authentik_url", "Authentik base URL", False),
         ("authentik_token", "Authentik API token", True)]),
    "okta": (
        'provider "okta" {\n  org_name  = var.okta_org_name\n'
        '  base_url  = var.okta_base_url\n  api_token = var.okta_api_token\n}\n',
        [("okta_org_name", "Okta org name (the part before the domain)", False),
         ("okta_base_url", "okta.com or oktapreview.com", False),
         ("okta_api_token", "Okta API token", True)]),
    "auth0": (
        'provider "auth0" {\n  domain        = var.auth0_domain\n'
        '  client_id     = var.auth0_client_id\n'
        '  client_secret = var.auth0_client_secret\n}\n',
        [("auth0_domain", "Auth0 tenant domain", False),
         ("auth0_client_id", "Management API client id", False),
         ("auth0_client_secret", "Management API client secret", True)]),
}


def _provider_tf(provider: str) -> str:
    source = load_schema(provider)["provider_source"]
    local = source.split("/")[-1]
    stub = _PROVIDER_STUBS[provider][0]
    return (f'terraform {{\n  required_providers {{\n    {local} = {{\n'
            f'      source = "{source}"\n    }}\n  }}\n}}\n\n{stub}')


def _variables_tf(provider: str, extra_vars: list) -> str:
    blocks = []
    for name, desc, sensitive in _PROVIDER_STUBS[provider][1]:
        s = "\n  sensitive   = true" if sensitive else ""
        blocks.append(f'variable "{name}" {{\n  type        = string\n'
                      f'  description = "{desc}"{s}\n}}')
    seen = set()
    for name, desc, vtype in extra_vars:
        if name in seen:
            continue
        seen.add(name)
        blocks.append(f'variable "{name}" {{\n  type        = {vtype}\n'
                      f'  description = "{_escape(desc)}"\n'
                      f"  sensitive   = true\n}}")
    return "\n\n".join(blocks) + "\n"


def export_object(provider: str, rtype: str, obj: dict) -> dict:
    """Single-object export for the Live State per-row Terraform view."""
    tf_type, reason = tf_resource_for(provider, rtype, obj)
    if not tf_type:
        return {"ok": False, "reason": reason,
                "name": display_name(provider, rtype, obj)}
    label = sanitize_label(display_name(provider, rtype, obj))
    hcl, dropped, variables = emit_resource(provider, tf_type, obj, rtype, label)
    oid = import_id(provider, rtype, tf_type, obj)
    return {"ok": True, "tf_type": tf_type, "label": label, "hcl": hcl,
            "import_block": emit_import(tf_type, label, oid) if oid else None,
            "dropped": dropped, "variables": [v[0] for v in variables],
            "name": display_name(provider, rtype, obj)}


def export_bundle(provider: str, export: dict, selected_rtypes: list,
                  tenant_name: str, snapshot_ts: str = "") -> tuple:
    """Full bundle export. Returns ({filename: content}, report).

    Two passes: first assign every exportable object a tf_type + label and
    index its id, then emit with cross-references resolved against that index.
    """
    labels = _Labels()
    planned, report = [], {"types": {}, "skipped": [], "total": 0}
    for rtype in selected_rtypes:
        objs = export.get(rtype) or []
        if isinstance(objs, dict):
            objs = [objs]  # singletons (auth0 tenant_settings/branding)
        for obj in objs:
            tf_type, reason = tf_resource_for(provider, rtype, obj)
            name = display_name(provider, rtype, obj)
            if not tf_type:
                report["skipped"].append((rtype, name, reason))
                continue
            label = labels.take(sanitize_label(name))
            planned.append((rtype, tf_type, label, obj))

    ref_index = {}
    for rtype, tf_type, label, obj in planned:
        oid = object_id(provider, rtype, obj)
        if oid is not None:
            ref_index[str(oid)] = (tf_type, label)

    files, imports, all_vars = {}, [], []
    dropped_by_type = {}
    for rtype, tf_type, label, obj in planned:
        hcl, dropped, variables = emit_resource(
            provider, tf_type, obj, rtype, label, ref_index)
        files.setdefault(f"{rtype}.tf", []).append(hcl)
        all_vars.extend(variables)
        if dropped:
            dropped_by_type.setdefault(rtype, set()).update(dropped)
        oid = import_id(provider, rtype, tf_type, obj)
        if oid is not None:
            imports.append(emit_import(tf_type, label, oid))
        t = report["types"].setdefault(rtype, {"exported": 0})
        t["exported"] += 1
        report["total"] += 1

    out = {name: "\n\n".join(blocks) + "\n" for name, blocks in files.items()}
    out["provider.tf"] = _provider_tf(provider)
    out["variables.tf"] = _variables_tf(provider, all_vars)
    if imports:
        out["import.tf"] = (
            "# Terraform 1.5+ import blocks: `terraform plan` adopts the\n"
            "# EXISTING objects into state instead of creating duplicates.\n"
            "# Remove this file when applying to a fresh/empty tenant.\n\n"
            + "\n\n".join(imports) + "\n")
    report["dropped_fields"] = {k: sorted(v) for k, v in dropped_by_type.items()}
    out["README.md"] = _readme(provider, tenant_name, snapshot_ts, report)
    return out, report


def _readme(provider: str, tenant_name: str, snapshot_ts: str,
            report: dict) -> str:
    src = load_schema(provider)["provider_source"]
    L = [f"# Terraform export - {tenant_name}", ""]
    if snapshot_ts:
        L.append(f"Generated by IdPVault from snapshot `{snapshot_ts}`.")
    else:
        L.append("Generated by IdPVault from the tenant's live state.")
    L += ["", f"Provider: `{src}` (official). Resources were emitted against",
          "the provider's own published schema; run `terraform init` then",
          "`terraform plan` to review before applying anything.", "",
          "## What you get", "",
          "- `provider.tf` / `variables.tf` - provider setup; credentials and",
          "  every secret are variables. IdPVault NEVER writes secret values",
          "  into HCL, even when it holds them.",
          "- one `.tf` file per resource type",
          "- `import.tf` - import blocks so `terraform plan` adopts your",
          "  existing objects instead of recreating them. Delete it when",
          "  applying this export to a different (fresh) tenant.",
          "- Commented lines inside resources are available fields that are",
          "  currently blank - kept so every argument is visible. Delete the",
          "  single # to use one (the line is already aligned); Terraform",
          "  ignores them as-is.", "",
          "## Coverage", ""]
    for rtype, t in sorted(report["types"].items()):
        L.append(f"- {rtype}: {t['exported']} exported")
    if report["skipped"]:
        L += ["", "### Not exported", ""]
        for rtype, name, reason in report["skipped"]:
            L.append(f"- {rtype} / {name}: {reason}")
    if report.get("dropped_fields"):
        L += ["", "### Fields not representable in the provider", "",
              "These exist in the IdPVault snapshot but have no argument in",
              "the official provider's schema (usually computed/read-only):", ""]
        for rtype, fields in sorted(report["dropped_fields"].items()):
            L.append(f"- {rtype}: {', '.join(fields)}")
    L += ["", "Cross-references between exported objects were rewritten to",
          "Terraform references; ids of objects NOT in this export remain",
          "literal source-instance values - review those before applying to",
          "a different tenant.", ""]
    return "\n".join(L)
